name: Fuzz Methods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fuzz:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install requests
        pip install pandas
        pip install PyYAML
        pip install bandit
    - name: Fuzz Methods
      run: |
        python fuzz.py
